import { z } from "zod";

export const templateFieldsSchema = z.object({
  label_width_mm: z.number().min(20).max(300),
  label_height_mm: z.number().min(20).max(300),
  auction_label_text: z.string().trim().min(1).max(30),
  show_auction: z.boolean(),
  show_cliente: z.boolean(),
  show_tiktok_name: z.boolean(),
  show_order_id: z.boolean(),
  show_price: z.boolean(),
  show_datetime: z.boolean(),
  show_qr: z.boolean(),
  order_auction: z.number().int().min(1).max(6),
  order_cliente: z.number().int().min(1).max(6),
  order_tiktok_name: z.number().int().min(1).max(6),
  order_order_id: z.number().int().min(1).max(6),
  order_price: z.number().int().min(1).max(6),
  order_datetime: z.number().int().min(1).max(6),
  auction_font_pt: z.number().min(4).max(40),
  customer_font_pt: z.number().min(4).max(40),
  tiktok_font_pt: z.number().min(4).max(40),
  order_font_pt: z.number().min(4).max(40),
  price_font_pt: z.number().min(4).max(40),
  date_font_pt: z.number().min(4).max(40),
  label_font_pt: z.number().min(4).max(40),
  qr_size_mm: z.number().min(5).max(80),
  line_spacing_mm: z.number().min(0).max(20),
  title_data_gap_mm: z.number().min(0).max(20),
  letter_spacing_pt: z.number().min(-2).max(10),
  label_col_width_mm: z.number().min(5).max(80),
  column_gap_mm: z.number().min(0).max(20),
  padding_mm: z.number().min(0).max(20),
});
